(define (make-point x y)
    (cons x y))
(define (x-point point)
    (car point))
(define (y-point point)
    (cdr point))

(define (make-segment start-point end-point)
    (cons start-point end-point))
(define (start-segment segment)
    (car segment))
(define (end-segment segment)
    (cdr segment))

(define (average a b)
    (/ (+ a b) 2))
(define (midpoint point1 point2)
    (make-point (average (x-point point1) (x-point point2))
                (average (y-point point1) (y-point point2))))
(define (midpoint-segment segment)
   (midpoint (start-segment segment) (end-segment segment)))

(define (print-point point)
    (newline)
    (display "(")
    (display (x-point point))
    (display ",")
    (display (y-point point))
    (display ")"))

(print-point (midpoint-segment (make-segment (make-point 1 2) (make-point 3 4))))