(define (max a b) 
    (if (> a b) a b)
)
(define (min a b) 
    (if (> a b) b a)
)
(define (make-interval a b) (cons a b))
(define (upper-bound interval) 
    (max (car interval) (cdr interval))
)
(define (lower-bound interval)
    (min (car interval) (cdr interval))
)